
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { useEffect } from "react";
import AOS from 'aos';
import 'aos/dist/aos.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MukuJiro",
  description: "Generated by mukuzai",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}
) {

  return (
    <html>
      <body className={inter.className}>
        {/* <div>header</div> */}
        {children}</body>
    </html>
  );
}
